# Generated by Django 2.1.5 on 2019-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190414_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltestanswer',
            name='status',
            field=models.BooleanField(blank=True, default=None, verbose_name='Статус правильности'),
        ),
        migrations.AlterField(
            model_name='modeltestirovanieuser',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус пройденности'),
        ),
    ]
