# Generated by Django 2.1.5 on 2019-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190416_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosch', models.TextField(blank=True, default='')),
                ('kis', models.TextField(blank=True, default='')),
                ('kts', models.TextField(blank=True, default='')),
                ('kav', models.TextField(blank=True, default='')),
                ('k_system', models.TextField(blank=True, default='')),
                ('k_inst_unist', models.TextField(blank=True, default='')),
                ('k_license', models.TextField(blank=True, default='')),
                ('k_update', models.TextField(blank=True, default='')),
                ('k_check', models.TextField(blank=True, default='')),
                ('kav_limit', models.TextField(blank=True, default='')),
                ('kis_limit', models.TextField(blank=True, default='')),
                ('kts_limit', models.TextField(blank=True, default='')),
                ('kpm', models.TextField(blank=True, default='')),
                ('kpm_inst_unist', models.TextField(blank=True, default='')),
                ('kpm_job', models.TextField(blank=True, default='')),
                ('kpm_face1', models.TextField(blank=True, default='')),
                ('kpm_face2', models.TextField(blank=True, default='')),
                ('kpm_license', models.TextField(blank=True, default='')),
                ('kpm_security', models.TextField(blank=True, default='')),
                ('kpm_task', models.TextField(blank=True, default='')),
                ('kpm_setting', models.TextField(blank=True, default='')),
                ('ksk', models.TextField(blank=True, default='')),
                ('ksk_inst_unist', models.TextField(blank=True, default='')),
                ('ksk_face', models.TextField(blank=True, default='')),
                ('ksk_license', models.TextField(blank=True, default='')),
                ('ksk_license2', models.TextField(blank=True, default='')),
                ('ksk_setting', models.TextField(blank=True, default='')),
                ('ksec', models.TextField(blank=True, default='')),
                ('ksec_system', models.TextField(blank=True, default='')),
                ('ksec_inst_unist', models.TextField(blank=True, default='')),
                ('ksec_license', models.TextField(blank=True, default='')),
                ('ksec_traffic', models.TextField(blank=True, default='')),
                ('ksec_setting', models.TextField(blank=True, default='')),
                ('myk', models.TextField(blank=True, default='')),
                ('myk_device1', models.TextField(blank=True, default='')),
                ('myk_device2', models.TextField(blank=True, default='')),
                ('myk_license', models.TextField(blank=True, default='')),
                ('myk_user', models.TextField(blank=True, default='')),
            ],
        ),
    ]
